### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by IsraArvin** [indigodavid/portfolio#11]
## Hi there 👋 
- This is a very nice project you have here! 💯 
- I believe it would be better if you use `querySelectorAll` instead of `querySelector` for your nav-links on line 4 -index.js- file.
this will help you apply the style for all of your nav links instead of the first child.

**Comment by masangana** [comment]
### Hello  @indigodavid 

@Masangana
You did a very great work. Your code are very clear and clean. 🥇 I think that you should
- Avoid long lines. for readability issues
- Use meaningful names for your classes. To allow others to directly understand your code
- For this module, you can Avoid the scrolling when your mobile is open.
check this code :

For **Css**
`.noscroll {
  position: fixed !important;
}` 

For **JS**
- Activate the effect
` page.classList.add('noscroll');`
- Remove the effect
`page.classList.remove('noscroll');`

💯 I love your job

**Comment by indigodavid** [comment]
Thanks for your kind observations. The latest merge solve this issues. About the classes I will work on them for the next milestone. Thanks again guys!! 👍
