### ISSUE TITLE
[BUG] Button links always opening the same modal

### ISSUE THREAD

**Issue by Andyveloper** [indigodavid/portfolio#15]
https://github.com/indigodavid/portfolio/blob/047fc939d41b4191ccb2433738f0185e24f12644/js/projects.js#L113

Please change the `javascript:openModal(${0})`; since this means it will always invoke openModal[0]

It should be `javascript:openModal(${index});` so it can iterate through the projects

**Comment by indigodavid** [comment]
The problem has been solved on the main branch. Thanks for your kind feedback.
