### ISSUE TITLE
Portfolio Deployment

### ISSUE THREAD

**Issue by indigodavid** [indigodavid/portfolio#8]
Below is the link to open the portfolio.

https://indigodavid.github.io/portfolio/

**Comment by keroloussamy** [comment]
Hi @indigodavid, 

Your project is complete!  There is nothing else to say
Congratulations! 🎉 

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by indigodavid** [comment]
@keroloussamy Thanks for your valuable feedback. It's encouraging to be part of such a great community.
